name: 001-deploy

on:
  workflow_dispatch:

env:
  LOCATION: "northeurope"
  RESOURCEGROUP: "rg-aks-001"

permissions:
  id-token: write
  contents: read

jobs:
  infra-rg:
    name: infra-rg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v2

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Create resource groups"
        run: |
          az group create --location "${{ env.LOCATION }}" -n "${{ env.RESOURCEGROUP }}"

  infra:
    name: infra
    runs-on: ubuntu-latest
    needs: infra-rg
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v2

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Deploy'
        run: |
          az deployment group create --template-file ./deploy/iac-gitops.bicep --name "aks-infra-deploy" --resource-group "${{ env.RESOURCEGROUP }}"
